### PR TITLE
Make Zotero Picker compatible again

### PR DESCRIPTION
**Pull request by SVNKoch**
I updated the zotero script. I wasn't able to import it anymore and recreated it.
I removed the shortcut "aaa" and menu part as well as they have no use.
PS: Whats the menu part about anyways? It didn'T seem to affect anything and wasn'T able to configure it in the UI either.

### CODE REVIEW

**Comment by octaeder** [comment]
I was able to load it from repo with Browse button:
grafik

You can create folder in the Macro Dialog and place Macros there. Then menu is set with a relative path:

grafik

```{
    "abbrev": "",
    "description": [
        "This macro lets you CAYW (Cite As You Write). Among other advantages, it lets you type anything which is contained in the references to retrieve them (and not only their citekeys as currently needed by the TeXstudio auto-completion). It needs Zotero (https://www.zotero.org/, to be open when used) and its (properly configured) Better Bibtex add-on (https://github.com/retorquere/zotero-better-bibtex), plus curl (https://curl.haxx.se/) which is available on numerous OSes. The following video lets you see this macro in action: https://youtu.be/Whn9Mk-JwL0. Enjoy!"
    ],
    "formatVersion": 2,
    "menu": "Folder",
    "name": "Launch Zotero Picker",
    "shortcut": "",
    "tag": [
        "var url = 'http://127.0.0.1:23119/better-bibtex/cayw??format=biblatex&command=autocite&texstudio=true&minimize=true';",
        "system('curl -s -A \"TeXstudio\" ' + url);"
    ],
    "trigger": "aaa",
    "type": "Script"
}
```

The folder can also be seen in the Macros menu of txs.

Be aware as stated with latest release notes that the format changed slightly with last release. Property formatVersion has been increased to 2 and Property type has been added. The type was previously encrypted in the first line of the macro code. When loading old formats they are converted automatically to the new format.

**Comment by sunderme** [comment]
I don't see any compatibility issues.
It simply loads ...

**Comment by octaeder** [comment]
I suggest not switching to Macro formatVersion 2 here if not necessary, because when the file is imported by older versions of txs the type attribute isn't recognized and type will be "normal" (snippet). But to be executable the type needs to be set to script manually then. You may edit the Json directly.

**Comment by SVNKoch** [comment]
hm, you are right, it does just load. Not sure what happened, maybe I accidentally changed something in the file beforehand?
Anyways I'll close the PR as it does work as expected.

**Pull request closed without merging**
